In [15]:
import pandas as pd
import numpy as np


callings=pd.read_csv("Data\sedec_chamados.csv",delimiter =';')

In [16]:
callings = callings.rename(columns={'processo_numero':'ID'})



callings.drop(columns='processo_origem', axis=1, inplace=True)

In [17]:
callings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45975 entries, 0 to 45974
Data columns (total 25 columns):
ano                           45975 non-null int64
mes                           45975 non-null object
ID                            45975 non-null int64
solicitacao_data              45975 non-null object
solicitacao_hora              45975 non-null object
solicitacao_descricao         45975 non-null object
solicitacao_regional          45964 non-null object
solicitacao_bairro            45975 non-null object
solicitacao_localidade        45798 non-null object
solicitacao_endereco          45971 non-null object
solicitacao_roteiro           45971 non-null object
rpa_codigo                    45975 non-null object
rpa_nome                      45975 non-null object
solicitacao_microrregiao      43356 non-null object
solicitacao_plantao           45975 non-null object
solicitacao_origem_chamado    45975 non-null object
latitude                      33009 non-null float64
longitude                     33009 non-null float64
solicitacao_vitimas           28651 non-null object
solicitacao_vitimas_fatais    28651 non-null object
processo_situacao             45919 non-null object
processo_tipo                 45975 non-null object
processo_localizacao          45971 non-null object
processo_status               45955 non-null object
processo_data_conclusao       9386 non-null object
dtypes: float64(2), int64(2), object(21)
memory usage: 5.1+ MB

In [18]:
callings.head()

,ano,mes,ID,solicitacao_data,solicitacao_hora,solicitacao_descricao,solicitacao_regional,solicitacao_bairro,solicitacao_localidade,solicitacao_endereco,...,solicitacao_origem_chamado,latitude,longitude,solicitacao_vitimas,solicitacao_vitimas_fatais,processo_situacao,processo_tipo,processo_localizacao,processo_status,processo_data_conclusao
0,2020,01-janeiro,8000001720,2020-01-01,05:56,TESTE DE ESPELHAMENTO AO QUIKVIEW 01 01 2020,PLANICIE,AFLITOS,AFLITOS,RUA AAA,...,Ocorrências,NaN,NaN,Não,Não,execucao,ATENDIMENTO,SEDEC - GERÊNCIA REGIONAL PLANICIE,TRAMITAÇÃO,NaN
1,2019,12-dezembro,8146602119,2019-12-10,08:23,USUÁRIO INFORMA QUE O SÍNDICO ESTÁ REALIZANDO ...,PLANICIE,AFLITOS,AFLITOS,"RUA CARNEIRO VILELA, 343",...,Ocorrências,NaN,NaN,Não,Não,completo,ATENDIMENTO,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/12/16 09:36:16.987
2,2019,12-dezembro,8146604419,2019-12-10,08:23,USUÁRIO INFORMA QUE O SÍNDICO ESTÁ REALIZANDO ...,PLANICIE,AFLITOS,AFLITOS,"RUA CARNEIRO VILELA, 343",...,Ocorrências,NaN,NaN,Não,Não,completo,ATENDIMENTO,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/12/10 08:48:09.749
3,2019,09-setembro,8112538919,2019-09-17,16:36,"USUÁRIO SOLICITA VISTORIA, INFORMA QUE SUA RES...",PLANICIE,AFLITOS,AFLITOS,"AV SANTOS DUMONT , N 290",...,Ocorrências,NaN,NaN,Não,Não,completo,ATENDIMENTO,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/09/20 11:14:10.615
4,2019,09-setembro,8109426919,2019-09-09,14:55,USUÁRIO INFORMA QUE QUE CASARÃO COSTA AZEVEDO ...,PLANICIE,AFLITOS,AFLITOS,AV CONS ROSA E SILVA N 707,...,Ocorrências,NaN,NaN,Não,Não,completo,ATENDIMENTO,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/09/16 14:40:50.180

In [19]:
callings.drop(columns='ano', axis=1, inplace=True)
callings.drop(columns='mes', axis=1, inplace=True)
callings.drop(columns='solicitacao_data', axis=1, inplace=True)
callings.drop(columns='solicitacao_descricao', axis=1, inplace=True)
callings.drop(columns='solicitacao_regional', axis=1, inplace=True)
callings.drop(columns='solicitacao_bairro', axis=1, inplace=True)
callings.drop(columns='solicitacao_localidade', axis=1, inplace=True)
callings.drop(columns='solicitacao_endereco', axis=1, inplace=True)
callings.drop(columns='solicitacao_roteiro', axis=1, inplace=True)
callings.drop(columns='rpa_codigo', axis=1, inplace=True)
callings.drop(columns='rpa_nome', axis=1, inplace=True)
callings.drop(columns='solicitacao_microrregiao', axis=1, inplace=True)
callings.drop(columns='solicitacao_plantao', axis=1, inplace=True)
callings.drop(columns='processo_tipo', axis=1, inplace=True)
callings.drop(columns='processo_situacao', axis=1, inplace=True)
callings.drop(columns='solicitacao_hora', axis=1, inplace=True)
callings.head()

,ID,solicitacao_origem_chamado,latitude,longitude,solicitacao_vitimas,solicitacao_vitimas_fatais,processo_localizacao,processo_status,processo_data_conclusao
0,8000001720,Ocorrências,NaN,NaN,Não,Não,SEDEC - GERÊNCIA REGIONAL PLANICIE,TRAMITAÇÃO,NaN
1,8146602119,Ocorrências,NaN,NaN,Não,Não,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/12/16 09:36:16.987
2,8146604419,Ocorrências,NaN,NaN,Não,Não,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/12/10 08:48:09.749
3,8112538919,Ocorrências,NaN,NaN,Não,Não,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/09/20 11:14:10.615
4,8109426919,Ocorrências,NaN,NaN,Não,Não,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/09/16 14:40:50.180

In [20]:
callings['solicitacao_vitimas'] = callings['solicitacao_vitimas'].astype('str')
callings['solicitacao_vitimas_fatais'] = callings['solicitacao_vitimas_fatais'].astype('str')

In [21]:
callings['solicitacao_vitimas']=[1 if sit == 'Sim' else 0 for sit in callings['solicitacao_vitimas']]
callings['solicitacao_vitimas_fatais']=[1 if sit == 'Sim' else 0 for sit in callings['solicitacao_vitimas_fatais']]

In [22]:
callings.head()

,ID,solicitacao_origem_chamado,latitude,longitude,solicitacao_vitimas,solicitacao_vitimas_fatais,processo_localizacao,processo_status,processo_data_conclusao
0,8000001720,Ocorrências,NaN,NaN,0,0,SEDEC - GERÊNCIA REGIONAL PLANICIE,TRAMITAÇÃO,NaN
1,8146602119,Ocorrências,NaN,NaN,0,0,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/12/16 09:36:16.987
2,8146604419,Ocorrências,NaN,NaN,0,0,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/12/10 08:48:09.749
3,8112538919,Ocorrências,NaN,NaN,0,0,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/09/20 11:14:10.615
4,8109426919,Ocorrências,NaN,NaN,0,0,SEDEC - GERÊNCIA REGIONAL PLANICIE,ARQUIVADO,2019/09/16 14:40:50.180

In [23]:
callings.drop(columns='solicitacao_origem_chamado', axis=1, inplace=True)
callings.drop(columns='processo_status', axis=1, inplace=True)
callings.drop(columns='processo_localizacao', axis=1, inplace=True)
callings.drop(columns='processo_data_conclusao', axis=1, inplace=True)
callings.head()

,ID,latitude,longitude,solicitacao_vitimas,solicitacao_vitimas_fatais
0,8000001720,NaN,NaN,0,0
1,8146602119,NaN,NaN,0,0
2,8146604419,NaN,NaN,0,0
3,8112538919,NaN,NaN,0,0
4,8109426919,NaN,NaN,0,0

In [24]:
callings = callings.rename(columns={'solicitacao_vitimas':'victims',
                                 'solicitacao_vitimas_fatais':'deadly_victims'})
callings.head()

           ID  latitude  longitude  victims  deadly_victims
0  8000001720       NaN        NaN        0               0
1  8146602119       NaN        NaN        0               0
2  8146604419       NaN        NaN        0               0
3  8112538919       NaN        NaN        0               0
4  8109426919       NaN        NaN        0               0

In [25]:
callings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45975 entries, 0 to 45974
Data columns (total 5 columns):
ID                45975 non-null int64
latitude          33009 non-null float64
longitude         33009 non-null float64
victims           45975 non-null int64
deadly_victims    45975 non-null int64
dtypes: float64(2), int64(3)
memory usage: 1.8 MB

In [26]:
callings = callings.drop_duplicates('ID')

In [27]:
callings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45975 entries, 0 to 45974
Data columns (total 5 columns):
ID                45975 non-null int64
latitude          33009 non-null float64
longitude         33009 non-null float64
victims           45975 non-null int64
deadly_victims    45975 non-null int64
dtypes: float64(2), int64(3)
memory usage: 2.1 MB

In [30]:
callings.fillna(0,inplace=True)
callings.head()

           ID  latitude  longitude  victims  deadly_victims
0  8000001720       0.0        0.0        0               0
1  8146602119       0.0        0.0        0               0
2  8146604419       0.0        0.0        0               0
3  8112538919       0.0        0.0        0               0
4  8109426919       0.0        0.0        0               0

In [31]:
callings['latitude'].value_counts()

 0.000000    12966
-8.110156     1424
-8.057838     1314
-7.999622     1271
-7.964835      834
             ...
-8.025835        1
-8.110822        1
-8.014195        1
-8.070477        1
-8.041324        1
Name: latitude, Length: 15750, dtype: int64

In [32]:
callings.to_csv(path_or_buf='callings_prepared.csv')